package com.lh.lhjuzhen.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lh.lhjuzhen.data.model.VideoIP;

import com.lh.lhjuzhen.data.DbDao.VideoIPDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoIPDaoConfig;

    private final VideoIPDao videoIPDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoIPDaoConfig = daoConfigMap.get(VideoIPDao.class).clone();
        videoIPDaoConfig.initIdentityScope(type);

        videoIPDao = new VideoIPDao(videoIPDaoConfig, this);

        registerDao(VideoIP.class, videoIPDao);
    }
    
    public void clear() {
        videoIPDaoConfig.clearIdentityScope();
    }

    public VideoIPDao getVideoIPDao() {
        return videoIPDao;
    }

}
