package com.lh.lhjuzhen.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.lhjuzhen.data.model.VideoIP;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO_IP".
*/
public class VideoIPDao extends AbstractDao<VideoIP, Void> {

    public static final String TABLENAME = "VIDEO_IP";

    /**
     * Properties of entity VideoIP.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property OutName = new Property(1, String.class, "outName", false, "OUT_NAME");
        public final static Property StrIp = new Property(2, String.class, "strIp", false, "STR_IP");
    }


    public VideoIPDao(DaoConfig config) {
        super(config);
    }
    
    public VideoIPDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO_IP\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"OUT_NAME\" TEXT," + // 1: outName
                "\"STR_IP\" TEXT);"); // 2: strIp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO_IP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoIP entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String outName = entity.getOutName();
        if (outName != null) {
            stmt.bindString(2, outName);
        }
 
        String strIp = entity.getStrIp();
        if (strIp != null) {
            stmt.bindString(3, strIp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoIP entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String outName = entity.getOutName();
        if (outName != null) {
            stmt.bindString(2, outName);
        }
 
        String strIp = entity.getStrIp();
        if (strIp != null) {
            stmt.bindString(3, strIp);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public VideoIP readEntity(Cursor cursor, int offset) {
        VideoIP entity = new VideoIP( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // outName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // strIp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoIP entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setOutName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStrIp(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(VideoIP entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(VideoIP entity) {
        return null;
    }

    @Override
    public boolean hasKey(VideoIP entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
